Multiplatform support inc. Windows; some cleanup
unInstance/untldr pull request #1
Opened 2021-12-03 06:00 UTC by bilditup1

Hi there,
I've been messing around with this since you released it--really wonderful how straightforward it is. I've managed to make a portable static build, too, at least for Windows, but want to make that code a bit nicer (this minimally involves changing the Makefile and possibly involves a configuration script). I have tried in the meantime to adhere to the code style per the readme. The other changes I've made are printing-related, and while I like the results, the code is not as elegant as your one liners, and there are a few other things I'd like to try there, too. 
In any case, this commit does a few things (though it isn't actually very long):
-It allows for untldr to build and run on Windows via mingw64 (so gcc, tested both 32- and 64-bit flavors) and makes some changes to console output mode specific to it; without doing this, ANSI/VT100 codes will either not be interpreted at all (in the regular Windows ConHost) or will be interpreted inconsistently (by the wonderful Windows Terminal app). These changes are otherwise minor (like adding a 'clear line from where the cursor is' command to RESET_STYLING, without which some styles, such as underlines, get displayed over empty space, right up until the next printf() statement, unfortunately), and do not cause issues for other platforms, and each change for Windows' sake was marked as such in the code. (Probably the most egregious of these was the need to explicitly invoke writing in binary mode, without which random CRLFs are chucked into the downloaded zip, corrupting it). 
--I did not mark the one change I had to make in the Makefile for this to work, namely, moving $(LDFLAGS) to the end of the `all` and `debug` commands, without which those libraries won't be found. 
-To run on platforms other than Linux, the dependency upon Linux's limits.h has been replaced with a generic <limits.h> include; this works on Windows (again at least via GCC, I have not tried clang, vs/ucrt, or any other C compiler on Windows), Debian Buster (gcc) and FreeBSD 12 (for this I installed gcc, but FreeBSD's default make uses clang, and I think that's what got used). I had initially had a long ifdef referring to the specific limits.h each platform used (see: https://arto.s3.amazonaws.com/notes/posix ) but simply using the generic one (presumably, part of the compiler's library) seemed like a more elegant solution. That said, leaving it out entirely has no effect on compilation and does not appear to affect performance, so that could be an option too--I'm not sure which constants from this file you wanted? I said all of this in a comment, too. 
-Makes changes to the zip files name and location. I wasn't sure why both the name and path of the temporary zip file were something easily configurable by the user. The zip file's name is of no real consequence given that it's not useful beyond the initial fetch (to this end, at end of decompression, I added a line deleting it entirely). The default "/tmp" in that case is a sane default only on *nix platforms where that path exists (yes, it's supposed to) and the user has not changed what the temporary directory is. (C:\tmp does not exist by default on Windows and attempting to write to it will error out if it isn't found.) So, I removed this configuration option from config.h and wrote a few lines querying the environment as to where the temporary directory was, using the common variable names for such a path on each platform, with"/tmp" as a failsafe--it is a POSIX standard after all.
-Renames a couple of variables in extract_pages() to make what they are a bit clearer (to me, anyway). 
-Fixes a typo ("Failer")
Hopefully, this is acceptable. I would rather contribute to this little project than maintain a fork. 
-Eli

2021-12-03 06:11 UTC, bilditup1 commented
One note, there is one case where I _know_ I didn't follow the style guide, when I defined global variables only used by functions defined on _WIN32 next to said functions, instead of near the top with all the other global variables. I thought keeping it as a self-contained unit there was more elegant than having multiple ifdefs, or defining them regardless of whether they were ever actually used and thus having the compiler throw a warning every time. Understood if you'd move them to the top regardless.

2022-01-02 08:25 UTC, unInstance requested changes
I am sorry it took to long for me to review your contribution; I am a student currently, so this is a rough time of the year for me.

Thank you for your wonderful job! I am also glad you can appreciate how simple this project is, this is by design.

Fix these little troubles I have mentioned within the code review, and I will gladly accept your changes.

2022-01-02 08:25 UTC, unInstance commented on tldr.c
> +char zip_path[BUF_SIZE];
This must be declared static.

2022-01-02 08:25 UTC, unInstance commented on tldr.c
> +#include <limits.h>
You are right, it is useless. Delete it.

2022-01-04 12:26 UTC, unInstance approved these changes
I can implement the required changes myself, there are not that many of them.

2022-01-04 12:26 UTC, merged

2022-01-04 18:26 UTC, bilditup1 commented
Sorry, I only just saw this now--hurray!